[package]
name = "tombi-schema-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
futures.workspace = true
glob.workspace = true
gloo-net = { workspace = true, optional = true }
itertools.workspace = true
log.workspace = true
reqwest = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tombi-accessor.workspace = true
tombi-ast-syntax = { workspace = true, optional = true }
tombi-cache.workspace = true
tombi-config.workspace = true
tombi-diagnostic.workspace = true
tombi-document-tree-syntax = { workspace = true, optional = true }
tombi-future.workspace = true
tombi-hashmap = { workspace = true, features = ["serde"] }
tombi-json.workspace = true
tombi-schema-type.workspace = true
tombi-severity-level.workspace = true
tombi-text.workspace = true
tombi-uri.workspace = true
tombi-x-keyword.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }
tombi-test-lib.workspace = true
tombi-config.workspace = true

[features]
default = ["native"]
ast-syntax = ["dep:tombi-ast-syntax"]
document-tree = ["dep:tombi-document-tree-syntax"]
gloo-net = ["dep:gloo-net"]
gloo-net06 = ["gloo-net"]
native = ["reqwest", "tombi-future/native"]
reqwest = ["dep:reqwest"]
reqwest01 = ["reqwest"]
wasm = ["gloo-net", "tombi-future/wasm"]

[lints]
workspace = true
