packages:
  - "docs"
  - "editors/vscode"
  - "typescript/@tombi-toml/*"
overrides:
  "@azure/msal-node": 5.2.2
  "@babel/core": 7.29.6
  "@vinxi/plugin-mdx>esbuild": 0.28.1
  "binary-install>axios": 0.31.1
  "binary-install>tar": 7.5.21
  browserslist: 4.28.7
  brace-expansion: 5.0.9
  dompurify: 3.4.13
  esbuild: 0.28.1
  fast-uri: 3.1.6
  form-data: 4.0.6
  h3: 1.15.11
  js-yaml: 4.3.2
  linkify-it: 5.0.2
  markdown-it: 14.2.0
  minimatch: 10.2.5
  nanoid: 3.3.18
  nitropack: 2.13.4
  postcss: 8.5.23
  qs: 6.16.0
  seroval: 1.5.3
  tar: 7.5.21
  tmp: 0.2.7
  undici: 7.29.0
  "vitest>vite": ^7.3.5
  ws: 8.21.0
minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - qs@6.16.0
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
allowBuilds:
  "@parcel/watcher": false
  "@vscode/vsce-sign": false
  esbuild: false
  keytar: false
  wasm-pack: false
