/* auto-generated by NAPI-RS */
/* eslint-disable */

/** The content of a `tombi.toml` config file at a given path. */
export interface ConfigFile {
  content: string
  path: string
}

/** A diagnostic reported by Tombi. */
export interface Diagnostic {
  level: "error" | "warning"
  code: string
  message: string
  range: Range
  sourceFile: string | null
}

/** Format a TOML document. */
export declare function format(source: string, sourcePath: string, options?: Options | undefined | null): Promise<FormatResult>

/** The result of formatting a TOML document. */
export interface FormatResult {
  /** The formatted source, or `undefined` if formatting failed. */
  formatted?: string
  diagnostics: Array<Diagnostic>
}

/** Format a TOML document synchronously, blocking the calling thread. */
export declare function formatSync(source: string, sourcePath: string, options?: Options | undefined | null): FormatResult

/** Lint a TOML document. */
export declare function lint(source: string, sourcePath: string, options?: Options | undefined | null): Promise<LintResult>

/** The result of linting a TOML document. */
export interface LintResult {
  diagnostics: Array<Diagnostic>
}

/** Lint a TOML document synchronously, blocking the calling thread. */
export declare function lintSync(source: string, sourcePath: string, options?: Options | undefined | null): LintResult

/** Options shared by the formatter and linter. */
export interface Options {
  /**
   * An in-memory `tombi.toml` configuration.
   * When a string is provided, it is treated as the content of a virtual
   * `tombi.toml`. When omitted, `tombi.toml` is searched from the current
   * working directory.
   */
  config?: string | ConfigFile
}

/** A zero-based position in a TOML document. */
export interface Position {
  line: number
  column: number
}

/** A range in a TOML document. */
export interface Range {
  start: Position
  end: Position
}
