[package]
name = "tombi-diagnostic"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nu-ansi-term.workspace = true
pyo3 = { workspace = true, optional = true }
serde.workspace = true
tombi-text.workspace = true
tower-lsp = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
clap.workspace = true
env_logger.workspace = true

[features]
default = ["lsp"]
lsp = ["dep:tower-lsp", "tombi-text/lsp"]
python = ["dep:pyo3"]
wasm = ["dep:wasm-bindgen", "tombi-text/wasm"]

[lints]
workspace = true
