[package]
name = "tombi-cache"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tombi-uri.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
tombi-test-lib.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dirs.workspace = true
log.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }

[lints]
workspace = true
