[package]
name = "tombi-uri"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
url = { version = "2.5.4", features = ["serde"] }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest.workspace = true

[target.'cfg(not(any(unix, windows, target_os = "redox", target_os = "wasi", target_os = "hermit")))'.dependencies]
percent-encoding.workspace = true

[lints]
workspace = true
