[package]
name = "tombi-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Tombi formatter, linter, and language server for WebAssembly"
repository.workspace = true
license.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook.workspace = true
futures = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }
js-sys.workspace = true
serde = { workspace = true, optional = true }
serde_tombi = { workspace = true, optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
tombi-config = { workspace = true, optional = true }
tombi-diagnostic = { workspace = true, optional = true }
tombi-formatter = { workspace = true, optional = true }
tombi-fs = { workspace = true, optional = true }
tombi-glob = { workspace = true, optional = true }
tombi-linter = { workspace = true, optional = true }
tombi-lsp = { workspace = true, optional = true }
tombi-schema-store = { workspace = true, optional = true }
tombi-uri = { workspace = true, optional = true }
tower-lsp = { workspace = true, optional = true }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
wasm-streams = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }

[features]
default = ["lib"]
lib = [
  "dep:itertools",
  "dep:serde",
  "dep:serde_tombi",
  "dep:serde-wasm-bindgen",
  "dep:tombi-config",
  "dep:tombi-diagnostic",
  "dep:tombi-formatter",
  "dep:tombi-fs",
  "dep:tombi-glob",
  "dep:tombi-linter",
  "dep:tombi-schema-store",
  "dep:tombi-uri",
  "serde_tombi/wasm",
  "tombi-diagnostic/wasm",
  "tombi-schema-store/wasm",
]
lsp = [
  "dep:futures",
  "dep:serde",
  "dep:serde-wasm-bindgen",
  "dep:tombi-fs",
  "dep:tombi-lsp",
  "dep:tombi-uri",
  "dep:tower-lsp",
  "dep:wasm-streams",
  "dep:web-sys",
  "tower-lsp/runtime-agnostic",
  "wasm-bindgen-futures/futures-core-03-stream",
  "web-sys/WritableStream",
  "web-sys/console",
]

[lints]
workspace = true
